# IMPORTING LIABARIES

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

READING DATASET:

In [2]:
data= pd.read_csv (r"D:\Nailya Thiran\data\data.csv",encoding='ISO-8859-1')

ANALYSE THE DATA

In [3]:
data.head()

Unnamed: 0  STATION CODE  \
0           1          1399   
1           2          1475   
2           3          3181   
3           4          3182   
4           5          1400   

                                           LOCATIONS STATE  Temp  D.O. (mg/l)  \
0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOI...   GOA  29.8          5.7   
1                                ZUARI AT PANCHAWADI   GOA  29.5          6.3   
2                        RIVER ZUARI AT BORIM BRIDGE   GOA  29.7          5.8   
3                       RIVER ZUARI AT MARCAIM JETTY   GOA  29.5          5.8   
4             MANDOVI AT NEGHBOURHOOD OF PANAJI, GOA   GOA  30.0          5.5   

    PH  CONDUCTIVITY (µmhos/cm)  B.O.D. (mg/l)  \
0  7.2                      189            2.0   
1  6.9                      179            1.7   
2  6.9                       64            3.8   
3  7.3                       83            1.9   
4  7.4                       81            1.5   

   NITRATENAN N+ NITRITENANN (mg/l)  FECAL COLIFORM (MPN/100ml)  \
0                               0.2                      4953.0   
1                               0.1                      3243.0   
2                               0.5                      5382.0   
3                               0.4                      3428.0   
4                               0.1                      2853.0   

   TOTAL COLIFORM (MPN/100ml)Mean  year  
0                          8391.0  2014  
1                          5330.0  2014  
2                          8443.0  2014  
3                          5500.0  2014  
4                          4049.0  2014

In [4]:
data.describe()

Unnamed: 0  STATION CODE        Temp  D.O. (mg/l)          PH  \
count   895.000000    895.000000  891.000000   895.000000  895.000000   
mean    494.671508   2189.115084   26.109315     6.312883    7.239866   
std     291.251441    804.883879    3.269947     1.294247    0.604587   
min       1.000000     17.000000   16.000000     0.200000    2.600000   
25%     246.500000   1548.000000   24.500000     5.900000    7.000000   
50%     488.000000   2289.000000   27.000000     6.700000    7.300000   
75%     755.500000   2707.000000   28.400000     7.100000    7.600000   
max    1216.000000   3473.000000   33.000000     9.900000    8.400000   

       CONDUCTIVITY (µmhos/cm)  B.O.D. (mg/l)  \
count               895.000000     893.000000   
mean               1699.711732       5.149776   
std                5103.103962      14.058354   
min                  27.000000       0.100000   
25%                  75.000000       1.200000   
50%                 162.000000       1.800000   
75%                 516.000000       3.300000   
max               44600.000000     185.800000   

       NITRATENAN N+ NITRITENANN (mg/l)  FECAL COLIFORM (MPN/100ml)  \
count                        890.000000                8.820000e+02   
mean                           1.636427                6.845984e+05   
std                            2.885759                1.207261e+07   
min                            0.000000                2.000000e+00   
25%                            0.280000                2.500000e+01   
50%                            0.590000                1.990000e+02   
75%                            1.750000                9.872500e+02   
max                           20.300000                2.725216e+08   

       TOTAL COLIFORM (MPN/100ml)Mean         year  
count                    8.840000e+02   895.000000  
mean                     1.104222e+06  2012.549721  
std                      2.063176e+07     1.094800  
min                      4.000000e+00  2010.000000  
25%                      8.975000e+01  2012.000000  
50%                      4.940000e+02  2013.000000  
75%                      2.395000e+03  2013.000000  
max                      5.110909e+08  2014.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Unnamed: 0                        895 non-null    int64  
 1   STATION CODE                      895 non-null    int64  
 2   LOCATIONS                         895 non-null    object 
 3   STATE                             895 non-null    object 
 4   Temp                              891 non-null    float64
 5   D.O. (mg/l)                       895 non-null    float64
 6   PH                                895 non-null    float64
 7   CONDUCTIVITY (µmhos/cm)           895 non-null    int64  
 8   B.O.D. (mg/l)                     893 non-null    float64
 9   NITRATENAN N+ NITRITENANN (mg/l)  890 non-null    float64
 10  FECAL COLIFORM (MPN/100ml)        882 non-null    float64
 11  TOTAL COLIFORM (MPN/100ml)Mean    884 non-null    float64
 12  year    

In [6]:
data.shape

(895, 13)

HANDLING MISSING VALUES

In [7]:
data.isnull().any()

Unnamed: 0                          False
STATION CODE                        False
LOCATIONS                           False
STATE                               False
Temp                                 True
D.O. (mg/l)                         False
PH                                  False
CONDUCTIVITY (µmhos/cm)             False
B.O.D. (mg/l)                        True
NITRATENAN N+ NITRITENANN (mg/l)     True
FECAL COLIFORM (MPN/100ml)           True
TOTAL COLIFORM (MPN/100ml)Mean       True
year                                False
dtype: bool

In [8]:
data.isnull().sum()

Unnamed: 0                           0
STATION CODE                         0
LOCATIONS                            0
STATE                                0
Temp                                 4
D.O. (mg/l)                          0
PH                                   0
CONDUCTIVITY (µmhos/cm)              0
B.O.D. (mg/l)                        2
NITRATENAN N+ NITRITENANN (mg/l)     5
FECAL COLIFORM (MPN/100ml)          13
TOTAL COLIFORM (MPN/100ml)Mean      11
year                                 0
dtype: int64

In [9]:
data.dtypes

Unnamed: 0                            int64
STATION CODE                          int64
LOCATIONS                            object
STATE                                object
Temp                                float64
D.O. (mg/l)                         float64
PH                                  float64
CONDUCTIVITY (µmhos/cm)               int64
B.O.D. (mg/l)                       float64
NITRATENAN N+ NITRITENANN (mg/l)    float64
FECAL COLIFORM (MPN/100ml)          float64
TOTAL COLIFORM (MPN/100ml)Mean      float64
year                                  int64
dtype: object

In [10]:
data['Temp']=pd.to_numeric(data['Temp'],errors='coerce')
data['D.O. (mg/l)']=pd.to_numeric(data['D.O. (mg/l)'],errors='coerce')
data['PH']=pd.to_numeric(data['PH'],errors='coerce')
data['B.O.D. (mg/l)']=pd.to_numeric(data['B.O.D. (mg/l)'],errors='coerce')
data['CONDUCTIVITY (µmhos/cm)']=pd.to_numeric(data['CONDUCTIVITY (µmhos/cm)'],errors='coerce')
data['NITRATENAN N+ NITRITENANN (mg/l)']=pd.to_numeric(data['NITRATENAN N+ NITRITENANN (mg/l)'],errors='coerce')
data['TOTAL COLIFORM (MPN/100ml)Mean']=pd.to_numeric(data['TOTAL COLIFORM (MPN/100ml)Mean'],errors='coerce')
data.dtypes

Unnamed: 0                            int64
STATION CODE                          int64
LOCATIONS                            object
STATE                                object
Temp                                float64
D.O. (mg/l)                         float64
PH                                  float64
CONDUCTIVITY (µmhos/cm)               int64
B.O.D. (mg/l)                       float64
NITRATENAN N+ NITRITENANN (mg/l)    float64
FECAL COLIFORM (MPN/100ml)          float64
TOTAL COLIFORM (MPN/100ml)Mean      float64
year                                  int64
dtype: object

In [11]:
data.isnull().sum()

Unnamed: 0                           0
STATION CODE                         0
LOCATIONS                            0
STATE                                0
Temp                                 4
D.O. (mg/l)                          0
PH                                   0
CONDUCTIVITY (µmhos/cm)              0
B.O.D. (mg/l)                        2
NITRATENAN N+ NITRITENANN (mg/l)     5
FECAL COLIFORM (MPN/100ml)          13
TOTAL COLIFORM (MPN/100ml)Mean      11
year                                 0
dtype: int64

In [12]:
data['Temp'].fillna(data['Temp'].mean(),inplace=True)
data['D.O. (mg/l)'].fillna(data['D.O. (mg/l)'].mean(),inplace=True)
data['PH'].fillna(data['PH'].mean(),inplace=True)
data['CONDUCTIVITY (µmhos/cm)'].fillna(data['CONDUCTIVITY (µmhos/cm)'].mean(),inplace=True)
data['B.O.D. (mg/l)'].fillna(data['B.O.D. (mg/l)'].mean(),inplace=True)
data['NITRATENAN N+ NITRITENANN (mg/l)'].fillna(data['NITRATENAN N+ NITRITENANN (mg/l)'].mean(),inplace=True)
data['TOTAL COLIFORM (MPN/100ml)Mean'].fillna(data['TOTAL COLIFORM (MPN/100ml)Mean'].mean(),inplace=True)

In [13]:
data.drop(["FECAL COLIFORM (MPN/100ml)"],axis=1,inplace=True)

In [14]:
data=data.rename(columns = {'D.O. (mg/l)': 'do'})
data=data.rename(columns = {'CONDUCTIVITY (µmhos/cm)': 'co'})
data=data.rename(columns = {'B.O.D. (mg/l)': 'bod'})
data=data.rename(columns = {'NITRATENAN N+ NITRITENANN (mg/l)': 'na'})
data=data.rename(columns = {'TOTAL COLIFORM (MPN/100ml)Mean': 'tc'})
data=data.rename(columns = {'STATION CODE': 'station'})
data=data.rename(columns = {'LOCATIONS': 'location'})
data=data.rename(columns = {'STATE': 'state'})
data=data.rename(columns = {'PH': 'ph'})

Water Quality Index (WQI) Calculation

In [15]:
#calculation of pH
data['npH']=data.ph.apply(lambda x: (100 if(8.5>=x>=7)
                                else(80 if(8.6>=x>=8.5) or (6.9>=x>=6.8)
                                  else (60 if(8.8>=x>=8.6) or (6.8>=x>=6.7)
                                      else(40 if(9>=x>=8.8) or (6.7>=x>=6.5)
                                          else 0)))))

In [16]:
#calculation of dissolved oxygen
data['ndo']=data.do.apply(lambda x: (100 if(x>=6)
                                else(80 if(6>=x>=5.1)
                                  else (60 if(5>=x>=4.1)
                                      else(40 if(4>=x>=3)
                                          else 0)))))

In [17]:
#calculation of total coliform
data['nco']=data.tc.apply(lambda x: (100 if(5>=x>=0)
                                else(80 if(50>=x>=5)
                                  else (60 if(500>=x>=50)
                                      else(40 if(10000>=x>=500)
                                          else 0)))))

In [18]:
#calculation of B.D.O
data['nbdo']=data.bod.apply(lambda x:(100 if(3>=x>=0)
                                else(80 if(6>=x>=3)
                                  else (60 if(80>=x>=6)
                                      else(40 if(125>=x>=80)
                                          else 0)))))

In [19]:
#calculation of electric conductivity
data['nec']=data.co.apply(lambda x:(100 if(75>=x>=0)
                                else(80 if(150>=x>=75)
                                  else (60 if(225>=x>=150)
                                      else(40 if(300>=x>=225)
                                          else 0)))))

In [20]:
#calculation of nitrate
data['nna']=data.na.apply(lambda x:(100 if(20>=x>=0)
                                else(80 if(50>=x>=20)
                                  else (60 if(100>=x>=50)
                                      else(40 if(200>=x>=100)
                                          else 0)))))

In [21]:
#Calculation of Water Quality Index WQI
data['wph']=data.npH*0.165
data['wdo']=data.ndo*0.281
data['wbdo']=data.nbdo*0.234
data['wec']=data.nec*0.009
data['wna']=data.nna*0.028
data['wco']=data.nco*0.281
data['wqi']=data.wph+data.wdo+data.wbdo+data.wec+data.wna+data.wco
data

Unnamed: 0  station                                           location  \
0             1     1399  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOI...   
1             2     1475                                ZUARI AT PANCHAWADI   
2             3     3181                        RIVER ZUARI AT BORIM BRIDGE   
3             4     3182                       RIVER ZUARI AT MARCAIM JETTY   
4             5     1400             MANDOVI AT NEGHBOURHOOD OF PANAJI, GOA   
..          ...      ...                                                ...   
890        1041     1148                                AMBIKA AT BILIMORA,   
891        1043     1438           MINDHOLA AT STATE HIGHWAY BRIDGE SACHIN,   
892        1209     1633                         SIMSANG RIVER WILLIAMNAGAR   
893        1215     1404                         GUMTI AT D/S SOUTH TRIPURA   
894        1216     1726   CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

       state  Temp    do    ph    co   bod    na  ...  nbdo  nec  nna   wph  \
0        GOA  29.8  5.70  7.20   189  2.00  0.20  ...   100   60  100  16.5   
1        GOA  29.5  6.30  6.90   179  1.70  0.10  ...   100   60  100  13.2   
2        GOA  29.7  5.80  6.90    64  3.80  0.50  ...    80  100  100  13.2   
3        GOA  29.5  5.80  7.30    83  1.90  0.40  ...   100   80  100  16.5   
4        GOA  30.0  5.50  7.40    81  1.50  0.10  ...   100   80  100  16.5   
..       ...   ...   ...   ...   ...   ...   ...  ...   ...  ...  ...   ...   
890  GUJARAT  28.4  6.20  7.80  7778  2.70  0.26  ...   100    0  100  16.5   
891  GUJARAT  28.3  3.20  7.70   885  6.30  0.51  ...    60    0  100  16.5   
892  MIZORAM  25.0  8.23  7.38   143  1.55  3.55  ...   100   80  100  16.5   
893  tripura  28.0  6.20  7.70   176  3.50  0.20  ...    80   60  100  16.5   
894  tripura  29.0  6.30  8.00   198  4.20  0.30  ...    80   60  100  16.5   

       wdo   wbdo   wec  wna    wco    wqi  
0    22.48  23.40  0.54  2.8  11.24  76.96  
1    28.10  23.40  0.54  2.8  11.24  79.28  
2    22.48  18.72  0.90  2.8  11.24  69.34  
3    22.48  23.40  0.72  2.8  11.24  77.14  
4    22.48  23.40  0.72  2.8  11.24  77.14  
..     ...    ...   ...  ...    ...    ...  
890  28.10  23.40  0.00  2.8  11.24  82.04  
891  11.24  14.04  0.00  2.8  11.24  55.82  
892  28.10  23.40  0.72  2.8  16.86  88.38  
893  28.10  18.72  0.54  2.8  11.24  77.90  
894  28.10  18.72  0.54  2.8  11.24  77.90  

[895 rows x 25 columns]

In [22]:
#Calculation of overall WQI for each year
average = data.groupby('year')['wqi'].mean()
average.head()

year
2010    75.292000
2011    77.763256
2012    77.899048
2013    78.031765
2014    77.844036
Name: wqi, dtype: float64

Splitting Dependent and Independent Columns

In [23]:
data.head()
data.drop(['location','station','state'],axis =1,inplace=True)

In [24]:
data.head()

Unnamed: 0  Temp   do   ph   co  bod   na      tc  year  npH  ...  nbdo  \
0           1  29.8  5.7  7.2  189  2.0  0.2  8391.0  2014  100  ...   100   
1           2  29.5  6.3  6.9  179  1.7  0.1  5330.0  2014   80  ...   100   
2           3  29.7  5.8  6.9   64  3.8  0.5  8443.0  2014   80  ...    80   
3           4  29.5  5.8  7.3   83  1.9  0.4  5500.0  2014  100  ...   100   
4           5  30.0  5.5  7.4   81  1.5  0.1  4049.0  2014  100  ...   100   

   nec  nna   wph    wdo   wbdo   wec  wna    wco    wqi  
0   60  100  16.5  22.48  23.40  0.54  2.8  11.24  76.96  
1   60  100  13.2  28.10  23.40  0.54  2.8  11.24  79.28  
2  100  100  13.2  22.48  18.72  0.90  2.8  11.24  69.34  
3   80  100  16.5  22.48  23.40  0.72  2.8  11.24  77.14  
4   80  100  16.5  22.48  23.40  0.72  2.8  11.24  77.14  

[5 rows x 22 columns]

In [25]:
x=data.iloc[:,0:7].values
x.shape

(895, 7)

In [26]:
y=data.iloc[:,-1:].values
y.shape

(895, 1)

In [27]:
print(x)

[[1.000e+00 2.980e+01 5.700e+00 ... 1.890e+02 2.000e+00 2.000e-01]
 [2.000e+00 2.950e+01 6.300e+00 ... 1.790e+02 1.700e+00 1.000e-01]
 [3.000e+00 2.970e+01 5.800e+00 ... 6.400e+01 3.800e+00 5.000e-01]
 ...
 [1.209e+03 2.500e+01 8.230e+00 ... 1.430e+02 1.550e+00 3.550e+00]
 [1.215e+03 2.800e+01 6.200e+00 ... 1.760e+02 3.500e+00 2.000e-01]
 [1.216e+03 2.900e+01 6.300e+00 ... 1.980e+02 4.200e+00 3.000e-01]]


In [28]:
print(y)

[[76.96]
 [79.28]
 [69.34]
 [77.14]
 [77.14]
 [75.44]
 [75.44]
 [82.04]
 [82.76]
 [82.58]
 [66.26]
 [68.22]
 [82.04]
 [82.94]
 [82.4 ]
 [82.58]
 [79.28]
 [76.16]
 [61.88]
 [55.02]
 [77.32]
 [28.12]
 [76.96]
 [76.78]
 [76.78]
 [76.34]
 [82.04]
 [55.02]
 [89.32]
 [89.32]
 [89.32]
 [89.32]
 [72.68]
 [77.36]
 [88.6 ]
 [72.68]
 [72.68]
 [83.7 ]
 [61.44]
 [73.04]
 [72.68]
 [77.36]
 [77.72]
 [78.66]
 [78.84]
 [78.66]
 [89.14]
 [88.6 ]
 [89.14]
 [89.32]
 [89.32]
 [77.9 ]
 [89.14]
 [89.14]
 [89.32]
 [88.38]
 [77.14]
 [88.56]
 [88.38]
 [85.26]
 [81.06]
 [79.64]
 [82.76]
 [82.58]
 [79.46]
 [82.76]
 [82.04]
 [82.76]
 [82.94]
 [55.28]
 [76.42]
 [88.38]
 [82.04]
 [85.08]
 [85.08]
 [51.36]
 [51.36]
 [88.56]
 [53.94]
 [82.4 ]
 [88.38]
 [82.94]
 [33.34]
 [88.56]
 [82.94]
 [76.34]
 [77.14]
 [82.04]
 [78.74]
 [85.26]
 [82.94]
 [82.94]
 [82.76]
 [79.64]
 [82.94]
 [88.38]
 [79.46]
 [73.04]
 [82.04]
 [79.64]
 [84.36]
 [82.04]
 [82.94]
 [88.56]
 [82.76]
 [79.64]
 [73.84]
 [68.4 ]
 [67.5 ]
 [82.94]
 [79.64]
 

Splitting the Data Into Train and Test

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=10)

Random_Forest_Regression

In [30]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [31]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

C:\Users\JESLIN MANO\AppData\Local\Temp\ipykernel_8416\3869103801.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train, y_train)


In [32]:
from sklearn import metrics
print('MAE:',metrics.mean_absolute_error(y_test,y_pred))
print('MSE:',metrics.mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

MAE: 3.38100558659218
MSE: 24.041909854748624
RMSE: 4.903255026484817


In [33]:
#accuracy of the model
metrics.r2_score(y_test, y_pred)

0.7933088615206914

Save The Model

In [34]:
import pickle
pickle.dump(regressor,open('wqi.pkl', 'wb'))
model = pickle.load(open('wqi.pkl','rb'))

In [35]:
open('wqi.pkl')

<_io.TextIOWrapper name='wqi.pkl' mode='r' encoding='cp1252'>